apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuan
  labels:
    auto_build_vpa: ye
spec:
  selector:
    matchLabels:
      app: puyuan
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: puyuan
        version: v1
    spec:
      containers:
      - name: puyuan
        image: everynamehavebeenuse/app1:pu
        imagePullPolicy: IfNotPresent
        command: ["python3","manage.py","runserver","0.0.0.0:80","--noreload"]

