apiVersion: v1
kind: Pod
metadata:
  name: atbvpa
spec:
  containers:
  - name: atbvpa
    image: atbvpa
    imagePullPolicy: Never
    command: ["/bin/bash"]
    args: ["-c", "python3 atb_vpa.py"]
      # - "sleep"
      # - "604800"
    # ports:
    # - containerPort: 388
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpagetlabel
rules:
- apiGroups: ["*"]
  resources: ["customobjects","namespaces","deployments","verticalpodautoscalers","pods" ]
  verbs: ["get","list","create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vpagetlabel
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: vpagetlabel
  apiGroup: rbac.authorization.k8s.io