apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels: 
        app: k6
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: k6-container
        image: everynamehavebeenuse/k6_docker
        ports:
        - containerPort: 50000


# 100-200级升级毒术的话，省钱推荐3（3n）天升级一次，因为黑炭蛆、天麟菇等太贵了不囤，除毒草外囤巴豆、麝香、砒霜、水银各30份（30n）以及饵料30份（捕捉绿蝎尾或红绒蚁），毒草囤若干，炼以下四个毒：
# 1、巴豆15份提炼15份巴豆粉 + 麝香30份 = 5份九香迷魂烟。
# 2、砒霜30份提炼15份砒霜散 + 狼毒花15份提炼断肠散15份 = 5份鹤顶红。
# 3、绿蝎尾15份提炼绿蝎粉15份 + 曼陀罗花10份 = 5份神仙倒。
# 4、首先水银30份提炼15份含九泉，接下来两个选择：
# A. + 红绒蚁15份提炼15份血里红 = 5份见血封喉；
# B. + 白毒伞10份提炼10份化功散 = 5份化骨吸髓。
# % 如果曼陀罗花囤的数量够，其实可以不囤红绒蚁，3天只抓绿蝎尾从而可以囤30份绿蝎尾，那么第3个毒可以绿蝎尾30份+曼陀罗花20份=10份神仙倒，而第4个毒可以只做B，这样每次升级时可以多炼5份毒。
# PS：wiki给出的攻略中按5天来升级，实际上不做黑炭蛆、天麟菇对应的毒的话，5天必然会导致商店售卖的巴豆等材料剩余，因为50除不开3嘛，这对于强迫症而言太难受了，而且还会多占背包格子，故推荐3天炼一次毒。