apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-scaledobject
spec:
  scaleTargetRef:
    name: puyuan
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://10.20.1.11:9090
      metricName: django_http_requests_total_by_method_total
      query: sum(rate(django_http_requests_total_by_method_total{instance="10.101.95.109:5000"}[1m]))
      threshold: '10'
      minReplicaCount: 1'
      maxReplicaCount: '10'
---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: workload-scaledobject
# spec:
#   scaleTargetRef:
#     name: puyuan
#   triggers:
#   - type: kubernetes-workload
#     metadata:
#       podSelector: 'app=puyuan'
#       value: '0.5'
#       activationValue: '1.1'
---