apiVersion: v1
kind: Pod
metadata:
  name: vpaget
spec:
  containers:
  - name: vpaget
    image: vpaget
    imagePullPolicy: Never
    command:
      - "sleep"
      - "604800"
    # ports:
    # - containerPort: 388
  - name: atbvpa
    image: atbvpa
    imagePullPolicy: Never
    command: ["/bin/bash"]
    args: ["-c", "python3 atb_vpa.py"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: ["*"]
  resources: ["customobjects","namespaces","deployments","verticalpodautoscalers","pods" ]
  verbs: ["get","list","create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
