apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: req
  template:
    metadata:
      labels:
        app: req
    spec:
      containers:
      - name: req-container
        command: ["/bin/sh","-c"]
        args: ["/home/script.sh"]
        image: everynamehavebeenuse/script-to-access-helloworld

